#+TITLE: EE4C10 Analog Circuit Design Fundamentals
#+SUBTITLE: RF Track
#+AUTHOR: Tzong Lin Chua
#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header: \usepackage[a4paper,left=0.5in,right=0.5in,top=0.5in,bottom=1in]{geometry}
#+latex_header: \usepackage{float}
#+LATEX_HEADER: \usepackage{enumerate}
#+latex_header_extra: \DeclareUnicodeCharacter{2212}{-}
#+latex_header_extra: \setcounter{secnumdepth}{0}
#+description:
#+keywords:
#+subtitle:
#+latex_compiler: pdflatex
#+date: \today
#+STARTUP: overview

* Simulation Files
Each question with simulation files will have their respective subfolder. The subsubfolder should be self-explainatory
depending on the question, (e.g., unmatched => unmatched LNA, r-matched => only resistive matching, matched => fully matched,
base => only used for testing (can be ignored, no plots made from this file)).

Running the simulation files should be able to directly plot the graphs used (configured in the *.plt file).
The folders for each question are arranged as follows after extracting:

|-------+----+----|
| spice |    |    |
|       | q1 |    |
|       |    | c  |
|       |    | d  |
|       | q2 |    |
|       |    | a  |
|       |    | b  |
|       | q4 |    |
|       |    | ab |
|       |    | c  |
|       |    | d  |
|       | q5 |    |
|       |    | a  |
|       | q6 |    |
|       |    | a  |
|       |    | b  |
|       |    | c  |
|       |    | d  |
|-------+----+----|
* Part 1
** Question 1
#+ATTR_LATEX: :options [A.]
A. Optimum gate width, $W_{g}$, for current budget of $12mA$.

   The maximum current,
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   I_{d,max} &= \frac{I_{total}}{N_{fingers} \cdot{} W_{g}} \\
   W_{g} &= \frac{I_{total}}{N_{fingers} \cdot{} I_{d,max}} \\
   &= 200 \mu{}m \\
   \end{aligned}
   \end{equation*}
   #+end_export

   In the case of 5 fingers,
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   W_{g,f} &= \frac{W_{g}}{N_{f}}
   &= 40 \mu{}m \\
   \end{aligned}
   \end{equation*}
   #+end_export

B. Highest $g_{m}$ of given current budget.

   $g_{m}$ for long channel devices,
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   g_{m} &= \frac{\partial I_{d}}{\partial V_{gs}} \\
   &\approx \sqrt{2\mu_{n}\C_{OX}\frac{W}{L}I_{D}} \\
   &\approx 0.0833 S \\
   \end{aligned}
   \end{equation*}
   #+end_export

C. Gate biasing conditions.

   Drain current of MOS transistor, using the parameters extracted from LTspice
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   i_{ds} &= \frac{\mu_{n}C_{OX}}{2}\frac{W}{L}(V_{gs} - V_{th})^{2}(1 + \lambda{}V_{ds}) \\
   V_{gs} &= \sqrt{\frac{2i_{ds}}{\mu_{n}C_{OX}}\frac{L}{W}\frac{1}{1 + \lambda{}V_{ds}}} + V_{th} \\
   &= 0.766 V \\
   \end{aligned}
   \end{equation*}
   #+end_export

   Parameter sweep in LTspice in Figure [[fig:id-vgs-q1]], gives a value of
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   V_{gs} &= 0.7 V \\
   i_{ds} &= 11.9 mA \\
   \end{aligned}
   \end{equation*}
   #+end_export

   $g_{m}$ in LTspice
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   g_{m} &= 0.0774 S \\
   \end{aligned}
   \end{equation*}
   #+end_export

   #+CAPTION: $I_{ds} - V_{gs}$ sweep
   #+NAME: fig:id-vgs-q1
   #+ATTR_LATEX: :placement [H]
   [[file:img/q1/id-vgs.pdf]]

D. Impedance at low frequency:
   1. Input, $R_{in} = \infty \Omega{}$

   2. Output, $R_{out} = r_{o} = \frac{1}{\lambda{} I_dmax} = 613 \Omega{}$

   The simulated input and output impedance from LTspice are shown in [[fig:zin-zout-q1]].
   It can be observed that $Z_{in}$ tends to infinity at low frequencies, while Z_{out} is
   around $603 \Omega{}$

   #+CAPTION: $Z_{in} and Z_{out} of amplifier$
   #+NAME: fig:zin-zout-q1
   #+ATTR_LATEX: :placement [H]
   [[file:img/q1/zin-zout-d.pdf]]

E. Capacitance of:
   #+ATTR_LATEX: :options [1.]
   a. $C_{gs}$

      #+begin_export latex
      \begin{equation*}
      \begin{aligned}
      C_{gs} &= \frac{2WLC_{OX}}{3} + WC_{OV} \\
      &= \frac{2W_{g}LC_{OX}}{3} + W_{g}C_{OV} \\
      &= 2.79 \times 10^{-13} F \\

      \end{aligned}
      \end{equation*}
      #+end_export

   b. $C_{gd}$

      #+begin_export latex
      \begin{equation*}
      \begin{aligned}
      C_{gd} &= WC_{OV} \\
      &= W_{g}C_{OV} \\
      &= 7.32 \times 10^{-14} F \\
      \end{aligned}
      \end{equation*}
      #+end_export

#+begin_comment
   $Z_{out}(V_{s})$ of the amplifier
   #+CAPTION: $Z_{out}(V_{s})$
   #+NAME: fig:zout-q1
   #+ATTR_LATEX: :placement [H]
   [[file:img/q1/rout.pdf]]
#+end_comment
#+begin_comment
A. Impedance at $5.5GHz$:
   A. Input, $Z_{in} = 2.81 - 45.94i \Omega{}$

   B. Ouput, $R_{out} = 49.98 - 73.59i \Omega{}$

   $Z_{out}(V_{s})$ of the amplifier
   #+CAPTION: $Z_{out}(V_{s})$
   #+NAME: fig:zout-q1
   #+ATTR_LATEX: :placement [H]
   [[file:img/q1/zin-zout.pdf]]
#+end_comment

#+begin_src python :exports none
import numpy as np
L = 0.18e-6
Nf = 5
unCox = 2.6 * 10**-4
Cox = 8.58 * 10**-3
Cov = 3.66 * 10**-10
lmbda = 0.136
I_dmax = 60
I_total = 12e-3
Vth = 5.08e-1

W_g = 12e-3/(I_dmax)

gm = np.sqrt(2*unCox*W_g*I_total/L)

V_gs = (2*I_total/(unCox))*(L/W_g)*(1/(1 + lmbda*1.8))
V_gs = np.sqrt(V_gs) + Vth

Cgs = (W_g*L*2*Cox/3 + W_g*Cov)
Cgd = W_g*Cov

Cin = Cgs + Cgd*(1 + 1.94)

L1 = 1/((2*np.pi*5.5e9)**2*Cin)

return [W_g, gm, V_gs, Cgs, Cgd, Cin, L1, 1/(lmbda * I_total)]
#+end_src

#+RESULTS:
| 0.0002 | 0.08326663997864532 | 0.7663392603205677 | 2.7912000000000003e-13 | 7.32e-14 | 4.94328e-13 | 1.693946436513625e-09 | 612.7450980392156 |

** Question 2
#+ATTR_LATEX: :options [A.]
A. Ohmic matching,
   #+ATTR_LATEX: :options [1]
   1. Input
      #+begin_export latex
      \begin{equation*}
      \begin{aligned}
      \frac{1}{R_{in,matched}} &= \frac{1}{R_{1}} + \frac{1}{R_{in}} \\
      \frac{1}{50} &= \frac{1}{R_{1}} \\
      R_{1} &= 50 \Omega \\
      \end{aligned}
      \end{equation*}
      #+end_export

   2. Output
      #+begin_export latex
      \begin{equation*}
      \begin{aligned}
      \frac{1}{R_{out,matched}} &= \frac{1}{R_{2}} + \frac{1}{R_{out}} \\
      \frac{1}{50} &= \frac{1}{R_{2}} + \frac{1}{603} \\
      R_{2} &= 54.5 \Omega \\
      \end{aligned}
      \end{equation*}
      #+end_export

B. Expected gain
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   G_{m} = g_{m} &= 0.0774 S \\
   R_{out} &= r_{o} // R_{2} // R_{L} \\
   &= 25 \Omega \\
   A_{V} &= -1.94 \\
   \end{aligned}
   \end{equation*}
   #+end_export

C. Input capacitance
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   C_{in} &= C_{gs} + \frac{C_{ds}}{1-A_{V}} \\
   &= 4.94 \times 10^{-13} F \\
   \end{aligned}
   \end{equation*}
   #+end_export

D. Matching input inductance, $L_{1}$.

   Input impedance
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   %\frac{1}{Z_{in}} &= \frac{1}{R_{1} + sL_{1}} + sC_{in} \\
   %Z_{in} &= \frac{R_{1} + sL_{1}}{1 + sR_{1}C_{in} - \omega^2L_{1}C_{in}} \\
   %\\
   L_{1} &\approx \frac{1}{\omega^2C_{IN}} \\
   &= 1.69 \times 10^{-9} H \\
   \end{aligned}
   \end{equation*}
   #+end_export

** Question 3
From previous section,
#+begin_export latex
\begin{equation*}
\begin{aligned}
G_{m} = g_{m} &= 0.0774 S \\
R_{out} &= r_{o} // R_{2} // R_{L} \\
&= 25 \Omega \\
A_{V} &= -1.94 \\
\end{aligned}
\end{equation*}
#+end_export

Noise figure, $F$,
#+begin_export latex
\begin{equation*}
\begin{aligned}
F &= 1 + \frac{N_{a}}{N_{i}G} \\
\\
N_{i} &= \overline{v_{R_{s}}^{2}} \\
&= \frac{4kT}{R_{s}}(R_{s} // R_{in})^{2} \\
&= \frac{4kT}{R_{s}}(R_{s} // R_{1})^{2} \\
\\
N_{a} &= \overline{v_{R_{1}}^{2}} + \overline{v_{M}^{2}} + \overline{v_{R_{2}}^{2}} \\
&= \frac{4kTR_{1}(R_{s} // R_{in})^{2}}{R_{1}}A_{v}^{2} + (4kT\gamma{}g_{m} + \frac{4kT}{R_{2}})R_{out}^{2} \\
&= 4kT[\frac{(R_{S} // R_{1})^{2}}{R_{1}}A_{v}^{2} + (\gamma{}g_{m} + \frac{1}{R_{2}})R_{out}^{2}] \\
\\
F &= 1 + \frac{\frac{(R_{S} // R_{1})^{2}}{R_{1}}A_{v}^{2} + (\gamma{}g_{m} + \frac{1}{R_{2}})R_{out}^{2}}{\frac{[(R_{s} // R_{1})A_{v}]^{2}}{R_{s}}} \\
&= 2.93 \\
&= 4.6 dB \\

\end{aligned}
\end{equation*}
#+end_export

#+begin_src python :exports none
R1 = 50
R2 = 54.5
Av = -1.94
Rout = 25
Rs = 50
gm = 0.0774
gamma = 2/3

F1 = ((Av*(R1*Rs)/(R1+Rs))**2)/R1 + (gamma*gm + 1/R2)*Rout**2
F2 = (Av*(Rs*R1)/(R1+Rs))**2/Rs
F = 1 + F1/F2

return [F1, F2, F]
#+end_src

#+RESULTS:
| 90.76288990825688 | 47.045 | 2.9292781360029094 |

** Question 4
#+ATTR_LATEX: :options [A.]
A. Ohmic matching. If the circuit is correctly matched the real part of the input impedance,
   $Re\{Z_{in}(f = 5.5GHz)\} = 50 \Omega$,
   the real part of the output impedance, $Re\{Z_{out}(f = 5.5GHz)\} = 50 \Omega$.
   The simulated $Z_{in}$ and $Z_{out}$ are shown in Figure [[fig:zin-zout-q4]],
   the matched impedance values are shown in [[tab:zin-zout-q4]].

   Since the resistance will also affect the resonanance frequency of an RLC circuit,
   the fine tuned values used are shown in Table [[tab:param-q4]].

B. Reactance matching. If the circuit is correctly matched the imaginary part of the input impedance,
   $Im\{Z_{in}(f = 5.5GHz)\} = 0 \Omega$,
   the imaginary part of the output impedance, $Im\{Z_{out}(f = 5.5GHz)\} = 0 \Omega$.
   The simulated $Z_{in}$ and $Z_{out}$ are shown in Figure [[fig:zin-zout-q4]],
   the matched impedance values are shown in [[tab:zin-zout-q4]].

   Since the resistance will also affect the resonanance frequency of an RLC circuit,
   the fine tuned values used are shown in Table [[tab:param-q4]].

   #+NAME: tab:zin-zout-q4
   #+CAPTION: Matched impedance at $f = 5.5GHz$
   |-----------+------------------------|
   | Impedance | Value                  |
   |-----------+------------------------|
   | $Z_{in}$  | $49.97 - 0.13i \Omega$ |
   | $Z_{out}$ | $49.69 - 0.15i \Omega$ |
   |-----------+------------------------|

   #+NAME: tab:param-q4
   #+CAPTION: Impedance matching parameters
   |-----------+-------------|
   | Parameter | Value       |
   |-----------+-------------|
   | $R_{1}$   | $49 \Omega$ |
   | $R_{2}$   | $53 \Omega$ |
   | $L_{1}$   | $1.65 nH$   |
   | $L_{2}$   | $3.99 nH$   |
   |-----------+-------------|

   #+CAPTION: $Z_{in}$ and $Z_{out}$
   #+NAME: fig:zin-zout-q4
   #+ATTR_LATEX: :placement [H]
   [[file:img/q4/zin-zout.pdf]]

C. S-parameters,
   #+ATTR_LATEX: :options [1)]
   1) No matching
      #+CAPTION: S-parameters without matching
      #+NAME: fig:s-unmatched-q4
      #+ATTR_LATEX: :placement [H]
      [[file:img/q4/s-unmatched.pdf]]

   2) Ohmic matching
      #+CAPTION: S-parameters with ohmic matching
      #+NAME: fig:s-r-match-q4
      #+ATTR_LATEX: :placement [H]
      [[file:img/q4/s-r-matched.pdf]]

   3) Ohmic and conjugate matching
      #+CAPTION: S-parameters with ohmic and conjugate matching
      #+NAME: fig:s-matched-q4
      #+ATTR_LATEX: :placement [H]
      [[file:img/q4/s-matched.pdf]]

D. Noise Factor,
   #+ATTR_LATEX: :options [1)]
   1) No matching
      #+CAPTION: Noise Factor without matching
      #+NAME: fig:noise-unmatched-q4
      #+attr_latex: :height 300px
      #+ATTR_LATEX: :placement [H]
      [[file:img/q4/noise-unmatched-2.pdf]]

   2) Ohmic matching
      #+CAPTION: Noise Factor with ohmic matching
      #+NAME: fig:noise-r-match-q4
      #+attr_latex: :height 300px
      #+ATTR_LATEX: :placement [H]
      [[file:img/q4/noise-r-matched-2.pdf]]

   3) Ohmic and conjugate matching
      #+CAPTION: Noise Factor with ohmic and conjugate matching
      #+NAME: fig:noise-matched-q4
      #+attr_latex: :height 300px
      #+ATTR_LATEX: :placement [H]
      [[file:img/q4/noise-matched-2.pdf]]

E. LNA performance using simplistic "design method".
   #+ATTR_LATEX: :options [1)]
   1) Advantages

      - Low refection coefficient, $S_{11} = -71 dB$.
      - Simple matching procedure due to uncorrelated input and output.

   2) Disadvantages.

      - Low gain, $S_{21} = 1.9 dB$.

      - High noise figure of $F \approx 5dB$.

      - The bandwith of the amplifier is small.

   
* Part 2
** Question 5
#+ATTR_LATEX: :options [A.]
A. From Question 1, the gate width, $W_{g}$, and gate bias voltage, $V_{gs}$,
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   W_{g} &= 200 \mu{}m \\
   V_{gs} &= 0.7 V \\
   \end{aligned}
   \end{equation*}
   #+end_export

   Input impedance of LNA,
   #+begin_export latex
   \begin{equation*}
   \begin{aligned}
   R_{in} &= \frac{V_{X}}{I_{X}} \\
   \\
   g_{m}V_{x} + \frac{V_{x} - I_{x}(R_{f}r_{o})}{r_{o}R_{L}} &= I_{x} \\
   V_{x}(g_{m} + \frac{r_{o} + R_{L}}{r_{o}R_{L}}) &= I_{X}(1 + \frac{R_{f}(r_{o} + R_{L})}{r_{o}R_{L}}) \\
   R_{f} &= \frac{R_{in}(r_{o} + R_{L} + g_{m}r_{o}R_{m}) - r_{o}R_{L}}{r_{o} + R_{L}} \\
   &= 182 \Omega \\
   \end{aligned}
   \end{equation*}
   #+end_export

B. The input impedance is matched using the reseistance of the single loop feedback,
   however, the output impedance is still unmatched. Since the task is to only match the input impedance,
   a single-loop feedback is sufficient.

C. Methods for improving the performance of the single loop feedback:
   - Using a cascode-stage. The input and output impedancences will be isolated,
     which will aid in the input and output impedance matching. However, the bias volatage has to be
     increased to maintain the current budget.

   - Adding an extra stage for increasing the overall gain of the amplifier, this will increase the power
     consumption.

   - From the slides, the 2 methods above can be combined with adding "phantom zeros" to increase or provide sufficient
     the gain bandwidth, which in the current design lacks.


#+begin_src python :exports none
import numpy as np
ro = 613
RL = 50
Rin = 50
gm = 0.0774

Rf = Rin*(ro + RL + gm*ro*RL) - ro*RL
Rf /= (ro + RL)
return Rf

#+end_src

#+RESULTS:
: 182.67797888386124

** Question 6
#+ATTR_LATEX: :options [A.]
A. Input and output impedance with $R_{f} = 182 \Omega$.

   #+CAPTION: Input and output impedance with resistive feedback, $R_{f} = 182 \Omega$.
   #+NAME: fig:zin-zout-r-matched-q6
   #+ATTR_LATEX: :placement [H]
   [[file:img/q6/zin-zout-r-matched.pdf]]

B. S-Parameters with $R_{f} = 182 \Omega$.

   #+CAPTION: S-parameters with resistive feedback, $R_{f} = 182 \Omega$.
   #+NAME: fig:s-r-matched-q6
   #+ATTR_LATEX: :placement [H]
   [[file:img/q6/s-r-matched.pdf]]

C. Noise figure with $R_{f} = 182 \Omega$.

   #+CAPTION: Noise figure with resistive feedback, $R_{f} = 182 \Omega$.
   #+NAME: fig:noise-r-matched-q6
   #+ATTR_LATEX: :placement [H]
   [[file:img/q6/noise-r-matched.pdf]]

D. 2 methods were attempted for designing the LNA:
   1. Matching $Z_{in} \approx 50 \Omega$ and $Z_{out} \approx 50 \Omega$ at 5.5GHz.
    After some fine tuning, the matching element values are shown in Table [[tab:param-q6d1]].
    The specifications of the resulting LNA are shown in Table [[tab:specs-q6d1]], with the simulated results in
    Figure [[fig:zin-zout-z-matched-q6]], [[fig:s-param-z-matched-q6]], and [[fig:noise-z-matched-q6]].
    #+NAME: tab:param-q6d1
    #+CAPTION: Impedance matching parameters for $Z_{in} \approx 50 \Omega$ and $Z_{out} \approx 50 \Omega$
    |-----------+--------------|
    | Parameter | Value        |
    |-----------+--------------|
    | $R_{f}$   | $154 \Omega$ |
    | $L_{in}$  | $1.2 nH$     |
    | $L_{out}$ | $2 nH$       |
    |-----------+--------------|

    #+NAME: tab:specs-q6d1
    #+CAPTION: LNA Specifications for matching parameters for $Z_{in} \approx 50 \Omega$ and $Z_{out} \approx 50 \Omega$
    |-------------------+----------------------|
    | Parameter         | Value                |
    |-------------------+----------------------|
    | $Z_{in}$          | $54.0 + 1.2i \Omega$ |
    | $Z_{out}$         | $47.9 + 0.9i \Omega$ |
    | $S_{11}$          | $-27.7 dB$           |
    | Gain, $S_{21}$    | $7.64 dB$            |
    | $S_{22}$          | $-32.7 dB$           |
    | Bandwidth, $BW$   | $> 1 GHz$            |
    | Noise Figure, $F$ | $3.4 dB$             |
    |-------------------+----------------------|

    #+CAPTION: Input and output impedance with $Z_{in} \approx 50 \Omega$ and $Z_{out} \approx 50 \Omega$
    #+NAME: fig:zin-zout-z-matched-q6
    #+ATTR_LATEX: :placement [H]
    [[file:img/q6/zin-zout-z-matched.pdf]]

    #+CAPTION: S-parameters with $Z_{in} \approx 50 \Omega$ and $Z_{out} \approx 50 \Omega$
    #+NAME: fig:s-param-z-matched-q6
    #+ATTR_LATEX: :placement [H]
    [[file:img/q6/s-z-matched.pdf]]

    #+CAPTION: Noise figure with $Z_{in} \approx 50 \Omega$ and $Z_{out} \approx 50 \Omega$
    #+NAME: fig:noise-z-matched-q6
    #+ATTR_LATEX: :placement [H]
    [[file:img/q6/noise-z-matched.pdf]]

   2. Matching the minimum of S11 and S22 to be at 5.5GHz.
      After some fine tuning, the matching element values are shown in Table [[tab:param-q6d2]].
      The specifications of the resulting LNA are shown in Table [[tab:specs-q6d1]], with the simulated results in
      Figure [[fig:zin-zout-s-matched-q6]], [[fig:s-param-s-matched-q6]], and [[fig:noise-s-matched-q6]].
    #+NAME: tab:param-q6d2
    #+CAPTION: Impedance matching parameters for minimum S_{11} and S_{22}.
    |-----------+--------------|
    | Parameter | Value        |
    |-----------+--------------|
    | $R_{f}$   | $182 \Omega$ |
    | $L_{in}$  | $1.3 nH$     |
    | $L_{out}$ | $2.5 nH$     |
    |-----------+--------------|

    #+NAME: tab:specs-q6d1
    #+CAPTION: LNA Specifications for matching parameters with minimum S_{11} and S_{22}.
    |-------------------+----------------------|
    | Parameter         | Value                |
    |-------------------+----------------------|
    | $Z_{in}$          | $58.8 - 2.5i \Omega$ |
    | $Z_{out}$         | $52.3 - 5.2i \Omega$ |
    | $S_{11}$          | $-21.6 dB$           |
    | Gain, $S_{21}$    | $8.7 dB$             |
    | $S_{22}$          | $-25.1 dB$           |
    | Bandwidth, $BW$   | $> 1 GHz$            |
    | Noise Figure, $F$ | $3.0 dB$             |
    |-------------------+----------------------|

    #+CAPTION: Input and output impedance with minimum S_{11} and S_{22}.
    #+NAME: fig:zin-zout-s-matched-q6
    #+ATTR_LATEX: :placement [H]
    [[file:img/q6/zin-zout-s-matched.pdf]]

    #+CAPTION: S-parameters with minimum S_{11} and S_{22}.
    #+NAME: fig:s-param-s-matched-q6
    #+ATTR_LATEX: :placement [H]
    [[file:img/q6/s-s-matched.pdf]]

    #+CAPTION: Noise figure with minimum S_{11} and S_{22}.
    #+NAME: fig:noise-s-matched-q6
    #+ATTR_LATEX: :placement [H]
    [[file:img/q6/noise-s-matched.pdf]]

E. The final design of the LNA have met the required specifications. However, the input and output
   impedance matching are not exactly $50 \Omega$. This can be improved using a cascode stage to
   isolate the input and output impedancences. On inspection, the bandwidth of the LNA is small,
   further improvements using "phantom zeroes" is most likely required.
